## Aprendedo Data Science Python

Let's have fun!!

In [1]:
print("Opa Mundão!!")

Opa Mundão!!


In [4]:
L = [1,3,4.9,"DINHEIRO",3]
T = (1,3,4.9,"name",3)
S = {1,3,4,9,"name",3}
D = {23:"twothree",'B':43,'C':'ccd'}

Numpy

In [5]:
import numpy as np

In [2]:
a = np.array([1,2,3,5,7])

In [4]:
b = np.array((2,3,4))

In [5]:
print(a)

[1 2 3]


In [8]:
print(a.ndim)

1


In [10]:
a = np.array([[1,2,3],[4,5,6]])


In [12]:
print(a[1,1])

5


In [13]:
a.ndim

2

In [14]:
b = np.array([[1,2,4,6],[1,9,2,5]])

In [15]:
b.ndim

2

In [16]:
b[0,3]

6

In [20]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]]])

In [21]:
c.ndim

3

In [23]:
c[1,1,2]

-6

In [25]:
A = np.arange(20,100,3)

In [26]:
print(A)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [32]:
A = np.random.permutation(np.arange(10))

In [33]:
A

array([1, 0, 9, 2, 4, 3, 8, 7, 5, 6])

In [42]:
np.random.randint(20,30)

22

In [44]:
A = np.random.rand(1000)

In [3]:
import matplotlib.pyplot as plt

In [4]:
plt.hist(A,bins=500)

NameError: name 'A' is not defined

In [49]:
E = np.random.rand(2,3)

In [50]:
E

array([[0.72413561, 0.04053956, 0.91639616],
       [0.59513609, 0.19610047, 0.62083008]])

In [51]:
E = np.random.rand(2,3,5,9)

In [52]:
E

array([[[[2.90637507e-01, 5.32884812e-01, 8.01536776e-01,
          1.65603419e-01, 9.40589967e-02, 5.15604432e-01,
          9.70656121e-01, 8.05503510e-01, 9.25779631e-01],
         [1.28112844e-01, 4.28757914e-01, 4.86640526e-01,
          4.71856780e-01, 5.88119065e-01, 5.96467075e-02,
          3.87550196e-01, 9.56776582e-01, 2.47012016e-01],
         [6.21225452e-01, 7.54805617e-01, 5.76265506e-01,
          8.29923729e-01, 7.36193415e-01, 5.93493725e-01,
          7.55344657e-01, 7.74680284e-01, 3.52901181e-01],
         [3.13407434e-01, 4.87221762e-01, 2.54423977e-02,
          7.03989176e-01, 5.32656812e-01, 4.64751939e-01,
          1.91407336e-01, 4.00121281e-01, 4.08167749e-01],
         [3.23022176e-01, 4.06742856e-01, 9.91217633e-01,
          8.28166125e-02, 9.39579516e-04, 8.60611102e-02,
          9.90583213e-01, 1.33316860e-01, 8.80755237e-01]],

        [[6.36631558e-01, 7.19780598e-01, 5.61072504e-01,
          4.48170648e-01, 6.61822543e-01, 8.06461271e-01,
       

In [6]:
A = np.arange(100)
print(A)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [58]:
b = A[3:10]
b

array([3, 4, 5, 6, 7, 8, 9])

In [61]:
b[2]= '222'

In [62]:
A

array([  0,   1,   2,   3,   4, 222,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [65]:
A[::-1]

array([ 99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,  87,
        86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,  74,
        73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,  61,
        60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,  48,
        47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,  35,
        34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,  22,
        21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,   9,
         8,   7,   6, 222,   4,   3,   2,   1,   0])

In [66]:
B = A==222*np.aran 

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

Estudar mais métodos de slicing

In [10]:
A = A -10

In [11]:
A

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
       80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94])

In [15]:
D = np.random.rand(1000000)
%timeit sum(D)
%timeit np.sum(D)
def mysum(D):
    s=0 
    for x in D:
        s+=x
%timeit mysum(D)


243 ms ± 27.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.96 ms ± 134 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
227 ms ± 2.99 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Pandas

Introdução a Pandas

In [16]:
import pandas as pd
data = pd.Series([0.25,0.5,0.75,1.0], index=['a','b','c','d'])

In [18]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [19]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [20]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [33]:
grades_dict = {'A':4,'A-':3.5,'B':3,'B-':2.5,'C':2}
grades = pd.Series(grades_dict)

In [34]:
grades.index


Index(['A', 'A-', 'B', 'B-', 'C'], dtype='object')

In [35]:
grades['A':'C']

A     4.0
A-    3.5
B     3.0
B-    2.5
C     2.0
dtype: float64

In [38]:
marks_dict = {'A':85,'A-':80,'B':75,'B-':70,'C':65}
marks = pd.Series(marks_dict)

In [39]:
D = pd.DataFrame({'Marks':marks, 'Grades': grades})

In [40]:
D

Marks  Grades
A      85     4.0
A-     80     3.5
B      75     3.0
B-     70     2.5
C      65     2.0

In [41]:
D.values[2,0]

75.0

In [43]:
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [44]:
D['ScaledMarks'] = D['Marks']*0.9

In [45]:
D

Marks  Grades  ScaledMarks
A      85     4.0         76.5
A-     80     3.5         72.0
B      75     3.0         67.5
B-     70     2.5         63.0
C      65     2.0         58.5

In [46]:
del D['ScaledMarks']

In [47]:
D

Marks  Grades
A      85     4.0
A-     80     3.5
B      75     3.0
B-     70     2.5
C      65     2.0

In [48]:
G = D[D['Marks']>70]

In [49]:
G

Marks  Grades
A      85     4.0
A-     80     3.5
B      75     3.0

In [51]:
A = pd.DataFrame([{'a':1,'b':4},{'b':3,'c':9}])

In [52]:
A

a  b    c
0  1.0  4  NaN
1  NaN  3  9.0

In [53]:
A.fillna(10000)

a  b        c
0      1.0  4  10000.0
1  10000.0  3      9.0

In [54]:
A.dropna

<bound method DataFrame.dropna of      a  b    c
0  1.0  4  NaN
1  NaN  3  9.0>

In [55]:
A

a  b    c
0  1.0  4  NaN
1  NaN  3  9.0

In [56]:
A.loc[1]

a    NaN
b    3.0
c    9.0
Name: 1, dtype: float64

In [61]:
A.iloc[0:1]

a  b   c
0  1.0  4 NaN

## Indo para o Mundo Real

Analisando dados da covid via Pandas

In [66]:
import pandas as pd
import numpy as np 
from sklearn.impute import SimpleImputer
df = pd.read_csv('caso_full.csv')

In [68]:
df.head(50)

city  city_ibge_code        date  epidemiological_week  \
0   Rio Branco       1200401.0  2020-03-17                202012   
1          NaN            12.0  2020-03-17                202012   
2   Rio Branco       1200401.0  2020-03-18                202012   
3          NaN            12.0  2020-03-18                202012   
4   Rio Branco       1200401.0  2020-03-19                202012   
5          NaN            12.0  2020-03-19                202012   
6   Rio Branco       1200401.0  2020-03-20                202012   
7          NaN            12.0  2020-03-20                202012   
8   Rio Branco       1200401.0  2020-03-21                202012   
9          NaN            12.0  2020-03-21                202012   
10  Rio Branco       1200401.0  2020-03-22                202013   
11         NaN            12.0  2020-03-22                202013   
12  Rio Branco       1200401.0  2020-03-23                202013   
13         NaN            12.0  2020-03-23                202013   
14  Rio Branco       1200401.0  2020-03-24                202013   
15         NaN            12.0  2020-03-24                202013   
16  Rio Branco       1200401.0  2020-03-25                202013   
17         NaN            12.0  2020-03-25                202013   
18  Rio Branco       1200401.0  2020-03-26                202013   
19         NaN            12.0  2020-03-26                202013   
20  Rio Branco       1200401.0  2020-03-27                202013   
21         NaN            12.0  2020-03-27                202013   
22  Rio Branco       1200401.0  2020-03-28                202013   
23         NaN            12.0  2020-03-28                202013   
24  Acrelândia       1200013.0  2020-03-29                202014   
25  Porto Acre       1200807.0  2020-03-29                202014   
26  Rio Branco       1200401.0  2020-03-29                202014   
27         NaN            12.0  2020-03-29                202014   
28  Acrelândia       1200013.0  2020-03-30                202014   
29  Porto Acre       1200807.0  2020-03-30                202014   
30  Rio Branco       1200401.0  2020-03-30                202014   
31         NaN            12.0  2020-03-30                202014   
32  Acrelândia       1200013.0  2020-03-31                202014   
33  Porto Acre       1200807.0  2020-03-31                202014   
34  Rio Branco       1200401.0  2020-03-31                202014   
35         NaN            12.0  2020-03-31                202014   
36  Acrelândia       1200013.0  2020-04-01                202014   
37  Porto Acre       1200807.0  2020-04-01                202014   
38  Rio Branco       1200401.0  2020-04-01                202014   
39         NaN            12.0  2020-04-01                202014   
40  Acrelândia       1200013.0  2020-04-02                202014   
41  Porto Acre       1200807.0  2020-04-02                202014   
42  Rio Branco       1200401.0  2020-04-02                202014   
43         NaN            12.0  2020-04-02                202014   
44  Acrelândia       1200013.0  2020-04-03                202014   
45  Porto Acre       1200807.0  2020-04-03                202014   
46  Rio Branco       1200401.0  2020-04-03                202014   
47         NaN            12.0  2020-04-03                202014   
48  Acrelândia       1200013.0  2020-04-04                202014   
49  Porto Acre       1200807.0  2020-04-04                202014   

    estimated_population  estimated_population_2019  is_last  is_repeated  \
0               413418.0                   407319.0    False        False   
1               894470.0                   881935.0    False        False   
2               413418.0                   407319.0    False        False   
3               894470.0                   881935.0    False        False   
4               413418.0                   407319.0    False        False   
5               894470.0                   881935.0    False        False   
6 